[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147" , features = ["derive"]}
serde_json = "1.0.87"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["json", ]
